-- MySQL Script generated by MySQL Workbench
-- Tue Feb 20 12:29:40 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema N1_Ejercicio1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema N1_Ejercicio1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `N1_Ejercicio1` DEFAULT CHARACTER SET utf8mb4 ;
USE `N1_Ejercicio1` ;

-- -----------------------------------------------------
-- Table `N1_Ejercicio1`.`Supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `N1_Ejercicio1`.`Supplier` (
  `name` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `mobile` INT NULL,
  `Fax` INT NULL,
  `NIF` VARCHAR(45) NULL,
  `idSupplier` INT NOT NULL,
  PRIMARY KEY (`idSupplier`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `N1_Ejercicio1`.`Customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `N1_Ejercicio1`.`Customers` (
  `idCustomer` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  `Postal address` VARCHAR(45) NULL,
  `Phone` INT NULL,
  `Email` VARCHAR(45) NULL,
  `Registration date` DATE NULL,
  `ReferredBy` VARCHAR(45) NULL,
  PRIMARY KEY (`idCustomer`),
  CONSTRAINT `ReferredBy`
    FOREIGN KEY (`idCustomer`)
    REFERENCES `N1_Ejercicio1`.`Customers` (`idCustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `N1_Ejercicio1`.`Brands`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `N1_Ejercicio1`.`Brands` (
  `idBrand` INT NOT NULL AUTO_INCREMENT,
  `Brandname` VARCHAR(45) NULL,
  `idSupplier` INT NULL,
  PRIMARY KEY (`idBrand`),
  INDEX `idSupplier_idx` (`idSupplier` ASC) VISIBLE,
  CONSTRAINT `idSupplier`
    FOREIGN KEY (`idSupplier`)
    REFERENCES `N1_Ejercicio1`.`Supplier` (`idSupplier`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `N1_Ejercicio1`.`Glasses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `N1_Ejercicio1`.`Glasses` (
  `Graduation` VARCHAR(45) NULL,
  `Frame materials` VARCHAR(45) NULL,
  `Color of frame` VARCHAR(45) NULL,
  `Color of each glass` VARCHAR(45) NULL,
  `Price` INT NULL,
  `idGlasses` INT NOT NULL,
  `idBrand` INT NULL,
  PRIMARY KEY (`idGlasses`),
  INDEX `idBrand_idx` (`idBrand` ASC) VISIBLE,
  CONSTRAINT `idBrand`
    FOREIGN KEY (`idBrand`)
    REFERENCES `N1_Ejercicio1`.`Brands` (`idBrand`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `N1_Ejercicio1`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `N1_Ejercicio1`.`Employee` (
  `idEmployee` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  `Position` VARCHAR(45) NULL,
  `HireData` DATE NULL,
  PRIMARY KEY (`idEmployee`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `N1_Ejercicio1`.`Sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `N1_Ejercicio1`.`Sales` (
  `idSales` INT NOT NULL AUTO_INCREMENT,
  `idEmployee` INT NULL,
  `idCustomer` INT NULL,
  `idGlasses` INT NULL,
  `SaleDate` DATE NULL,
  `Quantity` INT NULL,
  `TotalPrice` DECIMAL(10,2) NULL,
  PRIMARY KEY (`idSales`),
  INDEX `idEmployee_idx` (`idEmployee` ASC) VISIBLE,
  INDEX `idCustomer_idx` (`idCustomer` ASC) VISIBLE,
  INDEX `idGlasses_idx` (`idGlasses` ASC) VISIBLE,
  CONSTRAINT `idEmployee`
    FOREIGN KEY (`idEmployee`)
    REFERENCES `N1_Ejercicio1`.`Employee` (`idEmployee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idCustomer`
    FOREIGN KEY (`idCustomer`)
    REFERENCES `N1_Ejercicio1`.`Customers` (`idCustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idGlasses`
    FOREIGN KEY (`idGlasses`)
    REFERENCES `N1_Ejercicio1`.`Glasses` (`idGlasses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
